Content-Type:
    static:
        - image/png
        - image/svg+xml
        - image/jpeg
        - image/gif
        - image/bmp
        - image/tiff
        - application/javascript
        - application/x-javascript
        - application/json
        - text/css
        - application/pdf
        - application/msword
        - application/zip
        - text/yaml
        - application/xml
        - application/xhtml+xml
        - application/x-msdownload
        - binary/octet-stream
    dynamic:
        - text/html

headers:
    User-Agent:
        www: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'
        mobile: 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1'

default_timeout: 20

whitelist:
    host:
        - www.linkedin.com
        - www.miibeian.gov.cn
        - www.instagram.com
        - instagram.com
        - facebook.com
        - www.youtube.com
        - fonts.googleapis.com
        - twitter.com
        - www.apple.com
    fullurl:
        - https://cdn.ampproject.org
    startswith:
        - '#' # locator, e.g. #overview
        - 'javascript' # javascript:void(0);
        - 'mailto' # mailto:buyenterprise@debugtalk.com
        - 'tel:' # tel:00852+12345678
        - 'data:' # data:image/png;base64,iVBORw
        - 'whatsapp://' # whatsapp://send?text=https://store.XXX
    include-key:
        - xmlrpc.php
        - .link
        - .url
